version: "3.7"

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - db_data:/data/db 
  
  mongo-ui:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: 
      unless-stopped

  flask:
    build: ./api
    ports:
        - 9000:5000 
    environment: 
      - MONGO_HOST = mongo
      - MONGO_PORT = mongo
    restart:
        unless-stopped


# volumes: 
#   db_data:

